### ISSUE TITLE
Support for Project MMO

### ISSUE THREAD

**Issue by Druwan-ctrl** [jingshenSN2/CraftTime#3]
It would be awesome if this mod could be compatible with [PMMO](https://www.curseforge.com/minecraft/mc-mods/project-mmo) crafting levels and use them instead of the player level! 

This way it would allow a more stable and meaningful progression while doing various jobs

**Comment by jingshenSN2** [comment]
There are a few things I want to make sure of:
1. is PMMO compatible with this mod?
2. what is the normal range of PMMO's crafting level (normal means for most players they will stay in that range)? This will affect the speed_multiplier of PMMO. FYI: Since I believe that the normal player level range is 0~200, I set the speed_multiplier of the player level at 2% per level which means crafting speed varies from 1/tick to 5/tick.
3. I will keep the speed_multiplier of vanilla player level since not every player will install PMMO.

**Comment by Druwan-ctrl** [comment]
1) It seems to be, it takes experience with your crafting system
2) Each server/modpack owner can configure the max level between 1 and 150, more levels are not advised and the ones that go over 150 know how to change values accordingly
3) Sure, if I could have both I would give maybe a 0.05 global modifier or if possible completely disable it so the PMMO one takes over. PMMO also restricts what you can craft based on your level, so with this mod the more you get exp in crafting the faster you craft

**Comment by jingshenSN2** [comment]
ok, range: 1~150, multiplier: +5% per level. will be added in the next version.

**Comment by jingshenSN2** [comment]
Try 0.4.2~
